// 默认战队图标（用户提供的 favicon.ico 的 base64 内嵌）
// 内嵌而非运行时读 public/：保证 standalone 预构建、Vercel 等任何部署形态都能取到
// 模块级缓存 Buffer，避免每次请求重复解码
let cached: Buffer | null = null;

export function getDefaultFavicon(): Buffer {
  if (!cached) {
    cached = Buffer.from(
      "AAABAAEAICAAAAEACADECAAAFgAAACgAAAAgAAAAQAAAAAEACAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD8//8A+//+APv//ADj/cMA5f3JAK/6RwDh/bwA" +
      "/P/+APv//QDY/agAn/8PAOX9ygD2/vEAp/sxAJv/DgDl/MoAyfyFAJ7/DwCW9w4A5v3KAOz+2gCe+xwAlvgOAOv+2QDW/KYAu/xiAJ3/DwCX9hEA5v3LAMD8" +
      "bgCc/BUA8P7mAOD9vACZ+w4Al/cQAJn8DgDr/tQA6v3YAJv6FQDB/G8A+v/8AK37QgCX9xIAmPwOAKb7LgD3/vQAtvtXAJ3/DgCX9xEAmvsSAOb+yQDS/JoA" +
      "2/2vAN/9uwCc/w4AsvtNAPP+6gCj+igAmPoOALH7SwCp/DcAmv0OAJf2EgCc/w8Aw/x3AJf4EADp/dEA0PyVAKD/DwCY9hMAmvsQAJj4EQD1/vAA6P3PAJz7" +
      "FgCW9w8Awf1vAPD95gCf+x0Al/oOAKr7OgCe+hsAyfyDALb7VgDy/ucAnv8OAJ/7GwDv/eIAvPxlAOv92QDb/bAAm/8PAND8lgDo/dAAzvyUAJ77GwC6/GEA" +
      "9/71AKn7OACa/g4AlfYOAJ74IQDe/LcA3fy1AN/8uwDN/I4A3/25ANb8owCo/xAAn/8RAJj5EQCX9hMAovwfAN/8vQD4/vYAp/wvAJr/DgCt+0EA+v77AO7+" +
      "4ACg+yAAl/kOALP7UQDQ+5cA1fykAKX4MwCi/w8Aqvs7AO3+3QDW/aUA0f2ZAL79agCa+hMA5v3MAOT9xgC0+lQA9v7wALD7SgCi+iYA8v7pAOT9xQCZ+hAA" +
      "wvxyAPj++ACq/DMAvvtpAJr7EQCW9xAAw/x2ALD6SACi+yMA8P3kAPr/+wDN+5IAx/qDAL/9agCb+xUA6P7OAPv+/gDV/aMAmPcSANP8ngDp/dMAoPgnALX7" +
      "VAD0/u4AmPsOAJ/4IwDb/LIA3/y5AN79twDe/bYA4f2+AN39tgDe/rcA3f21AOT+xQC3+VwA2fytAPv+/QDH+38AlvcRAJz+EACd/xAAmf0OAKr8NQCd+xkA" +
      "mPgSAJj3EwCZ9xQAmPcUAM38jwC5/FkApf8QAJz/EQCc/xAApP0fAOr91QCt+UYArvlJAK75SACv+UoAqfg+AMv7jAD///8AAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAIQsbHyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjJyssAwMHCPz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/wxHExQAluiKgMLswvL28vLy8" +
      "vLy8vLy8vLy8vKAwMDC+Eb8AswC0ESpLS7W2P7c/Pz8/Pz8/Pz8/P7c/bpNLMLi5LQAAAKUspjB5p6ipqqqrrK2uqqqqqqqqr7CxDjAwW7IAswABAJ8/oDB0" +
      "oQAIAHKiAAAAAAAAAAAAi6NPPjakAAAAAAAAAJUOKjqWlwCYAJmaAAcIAQgHKACbCipLnJ0AngAAAAEAjI1LKhGOAAcAj5CRAAABAAEAhpKTKhGUAAcAAAAA" +
      "AAEAgxEqS4SFACgAhhGHiAABAACJNio6iosAAAAAAAAAAAB3eHkqNnoAWnt8fX5/gAAAgRowGxGCAAgAAAAAAAAACABpESowGmprbG1ubwpwcXJzIyp0dXYA" +
      "AAAAAAAAAAAAAGFiYyo9PC07Y2RlZmdCUhEqIiNoAAcAAAAAAAAAAAAHAFpbMCoKXF0hMA5eABRfFiovYAAAAAAAAAAAAAAAAAAAAFMvKhZOVB1VS1ZXWBEq" +
      "EhVZAAEAAAAAAAAAAAAAAAEASUpLKhFMTU4ST1BRSyoRUgAIAAAAAAAAAAAAAAAAAAcAQBEqQSFCQ0RFRkcwIw1IAAAAAAAAAAAAAAAAAAAAAAA4OToqNjst" +
      "PD0+IjA/CQAIAAAAAAAAAAAAAAAAAAAACAAzERswETQ1GjAbNjcAAAAAAAAAAAAAAAAAAAAAAAAAACgpDiorLC0uLzAxMgABAAAAAAAAAAAAAAAAAAAAAAAH" +
      "ACAhIiIjJCUmCicAAQAAAAAAAAAAAAAAAAAAAAAAAAABABkaGxYcAB0eHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAFBUWFhMAFxgAAQAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAgAEBESEwAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDQ4PAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAJCgsAAQAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAFBgAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAMEAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQIAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
      "AAAAAAAAAAAAAAAAAAAAAA==",
      'base64'
    );
  }
  return cached;
}
